# Generated by Django 3.2.8 on 2021-10-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras_Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=60, verbose_name='Descrição')),
                ('numero', models.IntegerField(max_length=20, verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observaçoes')),
            ],
            options={
                'verbose_name': 'Compras - Locaçao',
                'verbose_name_plural': 'Compras - Locaçao',
            },
        ),
        migrations.CreateModel(
            name='TRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numeroTRP', models.IntegerField(max_length=10, verbose_name='Número da TRP')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('data_fim_contrato', models.DateField(verbose_name='Data Final do Contrato')),
                ('data_fim_contrato_pror', models.DateField(verbose_name='Data Final do Contrato prorrogado')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observaçoes')),
            ],
            options={
                'verbose_name': 'TRP',
                'verbose_name_plural': 'TRPs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='locacao_acao',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observaçoes')),
                ('compras_loc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.compras_locacao')),
                ('fornecedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='EndFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('logradouro', models.CharField(max_length=60, verbose_name='Logradouro')),
                ('numero', models.IntegerField(max_length=10, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=60, verbose_name='Complemento')),
                ('CEP', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=60, verbose_name='Estado')),
                ('pais', models.CharField(max_length=60, verbose_name='Pais')),
                ('fornecedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Endereço de Fornecedor',
                'verbose_name_plural': 'Endereços de Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ContFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('Nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('email', models.CharField(max_length=60, verbose_name='E-mail')),
                ('observacoes', models.CharField(max_length=10, verbose_name='Observações')),
                ('fornecedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Contato de Fornecedor',
                'verbose_name_plural': 'Contatos de Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='compras_locacao',
            name='locacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.locacao_acao', verbose_name='ação'),
        ),
        migrations.AddField(
            model_name='compras_locacao',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='compras_locacao',
            name='trp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.trp', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='CatFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('fornecedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Categoria de Fornecedor',
                'verbose_name_plural': 'Categorias de Fornecedores',
            },
        ),
    ]
