# Generated by Django 3.2.8 on 2021-10-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211013_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endfornecedor',
            name='numero',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='trp',
            name='numeroTRP',
            field=models.IntegerField(verbose_name='Número da TRP'),
        ),
    ]
