# Generated by Django 3.2.8 on 2021-10-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211013_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contfornecedor',
            old_name='Nome',
            new_name='nome',
        ),
    ]
