# Generated by Django 3.2.8 on 2021-10-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_contfornecedor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='trp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.trp', verbose_name='tRP'),
        ),
    ]
