# Generated by Django 3.2.8 on 2021-10-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_compras_locacao_trp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('dataabertura', models.DateField(verbose_name='Data de Abertura')),
                ('datapregao', models.DateField(verbose_name='Data do Pregão')),
                ('dataassinatura', models.DateField(verbose_name='Data da Assinatura')),
                ('datahomologacao', models.DateField(verbose_name='Data de Homologação')),
                ('vencedor', models.CharField(max_length=50, verbose_name='Vencedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
            },
        ),
        migrations.CreateModel(
            name='DCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=50, verbose_name='Vencedor')),
                ('dataminuta', models.DateField(verbose_name='Data Minuta')),
                ('datadca', models.DateField(verbose_name='Data DCA')),
                ('anotacoes', models.CharField(max_length=50, verbose_name='Anotaçoes')),
                ('licitacao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.licitacao', verbose_name='Licitação')),
                ('locacao_acao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.locacao_acao', verbose_name='Solicitação')),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'DCA',
                'verbose_name_plural': 'DCAs',
            },
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('setor', models.CharField(max_length=50, verbose_name='Observaçoes')),
                ('data', models.DateField(verbose_name='Data')),
                ('dca', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.dca', verbose_name='DCA')),
            ],
            options={
                'verbose_name': 'Aprovaçao',
                'verbose_name_plural': 'Aprovaçoes',
            },
        ),
    ]
