# Generated by Django 3.2.8 on 2021-10-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aprovacao_dca_licitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Pagamento',
                'verbose_name_plural': 'Tipos de Pagamento',
            },
        ),
        migrations.AlterField(
            model_name='dca',
            name='anotacoes',
            field=models.CharField(max_length=100, verbose_name='Anotaçoes'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parcela')),
                ('qtde_parcelas', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dataprevnota', models.DateField(verbose_name='Data Prev Nota')),
                ('tiponota', models.CharField(max_length=5, verbose_name='Tipo da nota')),
                ('numnota', models.IntegerField(verbose_name='Numero da Nota')),
                ('dataemissnota', models.DateField(verbose_name='Data de Emisso da Nota')),
                ('serienota', models.CharField(max_length=100, verbose_name='Série da Nota')),
                ('xml', models.CharField(max_length=100, verbose_name='XML')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('tipo_pagto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.tipopagto', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('datainicio', models.DateField(verbose_name='Data Inicial')),
                ('datafim', models.DateField(verbose_name='Data Final')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('locacao_acao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.locacao_acao', verbose_name='Solicitação')),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cronogramas',
                'verbose_name_plural': 'Cronogramas',
            },
        ),
        migrations.CreateModel(
            name='Contrato_Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('processo', models.CharField(max_length=50, verbose_name='Processo')),
                ('dataprocesso', models.DateField(verbose_name='Data do Processo')),
                ('instrcontratual', models.CharField(max_length=50, verbose_name='Instrumento Contratual')),
                ('datacontrato', models.DateField(verbose_name='Data do Contrato')),
                ('valorservico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('valorlocacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Locação')),
                ('locacao_acao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.locacao_acao', verbose_name='Solicitação')),
                ('pagto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.pagamento', verbose_name='Pagamento')),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contrato Locação',
                'verbose_name_plural': 'Contratos Locação',
            },
        ),
    ]
