# Generated by Django 3.2.8 on 2021-10-16 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211013_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_acao',
            name='datasolicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Solicitação'),
            preserve_default=False,
        ),
    ]
