# Generated by Django 3.2.8 on 2021-10-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_locacao_acao_datasolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='aprovacao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='catfornecedor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='compras_locacao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='contfornecedor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='contrato_locacao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='dca',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='endfornecedor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='local',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='status',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='tipo_status',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='tipolocacao',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='tipopagto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='trp',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
    ]
