# Generated by Django 3.2.8 on 2021-10-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211016_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linguagem', verbose_name='linguagem'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local', verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto', verbose_name='projeto'),
        ),
    ]
