# Generated by Django 3.2.8 on 2021-10-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211017_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catfornecedor',
            name='cnpj',
        ),
    ]
