# Generated by Django 3.2.8 on 2021-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_catfornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
    ]
