# Generated by Django 3.2.8 on 2021-10-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_compras_locacao_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao_acao',
            name='status',
        ),
        migrations.AddField(
            model_name='locacao_acao',
            name='status_geral',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='status geral'),
            preserve_default=False,
        ),
    ]
