# Generated by Django 3.2.8 on 2021-10-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_compras_locacao_trp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=50, verbose_name='Vencedor')),
                ('dataminuta', models.DateField(verbose_name='Data Minuta')),
                ('datadca', models.DateField(verbose_name='Data DCA')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('licitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.licitacao', verbose_name='Licitação')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.RemoveField(
            model_name='aprovacao',
            name='dca',
        ),
        migrations.AlterField(
            model_name='acao',
            name='linguagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linguagem', verbose_name='linguagem'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local', verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projeto', verbose_name='projeto'),
        ),
        migrations.AlterField(
            model_name='catfornecedor',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='compras_locacao',
            name='locacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao', verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='compras_locacao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contfornecedor',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='contrato_locacao',
            name='locacao_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao', verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='contrato_locacao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='locacao_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao', verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='endfornecedor',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acao', verbose_name='açao'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='memorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.memorial', verbose_name='memorial'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='status_geral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='status geral'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='tipo_locacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipolocacao', verbose_name='tipo de Locaçao'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='compras_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compras_locacao'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopagto', verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='locacao_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao'),
        ),
        migrations.AlterField(
            model_name='status',
            name='tipo_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo_status', verbose_name='tipo de Status'),
        ),
        migrations.DeleteModel(
            name='DCA',
        ),
        migrations.AddField(
            model_name='sede',
            name='locacao_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='sede',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='aprovacao',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede', verbose_name='Sede'),
        ),
    ]
