# Generated by Django 3.2.8 on 2021-10-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211023_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_acao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Status', to='core.status', verbose_name='status'),
        ),
    ]
