# Generated by Django 3.2.8 on 2021-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_locacao_acao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='observacoes',
            field=models.CharField(max_length=100, null=True, verbose_name='Observaçoes'),
        ),
    ]
