# Generated by Django 3.2.8 on 2021-10-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_compras_locacao_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='descricao',
            field=models.CharField(default='', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='observacoes',
            field=models.CharField(default='', max_length=100, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='projeto',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projeto', verbose_name='projeto'),
        ),
        migrations.AlterField(
            model_name='compras_locacao',
            name='observacoes',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Observaçoes'),
        ),
        migrations.AlterField(
            model_name='compras_locacao',
            name='trp',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trp', verbose_name='tRP'),
        ),
    ]
