# Generated by Django 3.2.8 on 2021-10-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211025_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao_acao',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Descriçao'),
        ),
    ]
