# Generated by Django 3.2.8 on 2021-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_compras_locacao_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_locacao',
            name='sede',
            field=models.BooleanField(default=False, verbose_name='Sede'),
            preserve_default=False,
        ),
    ]
