# Generated by Django 3.2.8 on 2021-10-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_compras_locacao_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='trp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trp', verbose_name='tRP'),
        ),
    ]
