# Generated by Django 3.2.8 on 2021-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_compras_locacao_trp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacao',
            name='descricao',
            field=models.CharField(default='Descriçaão', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=50, verbose_name='Descriçao'),
            preserve_default=False,
        ),
    ]
