# Generated by Django 3.2.8 on 2021-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211028_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
    ]
