# Generated by Django 3.2.8 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_sede_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='descricao',
            field=models.CharField(default='Descrição Sede', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
