# Generated by Django 3.2.8 on 2021-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sede_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato_locacao',
            old_name='locacao_acao',
            new_name='locacao',
        ),
        migrations.AddField(
            model_name='contrato_locacao',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
