# Generated by Django 3.2.8 on 2021-10-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211028_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
