# Generated by Django 3.2.8 on 2021-10-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pagamento_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='locacao_acao',
            new_name='locacao',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
    ]
