# Generated by Django 3.2.8 on 2021-10-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20211028_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='locacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao_acao', verbose_name='Solicitação'),
        ),
    ]
