# Generated by Django 3.2.8 on 2021-10-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_pagamento_locacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato_locacao',
            name='pagto',
        ),
    ]
