# Generated by Django 3.2.8 on 2021-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_contrato_locacao_pagto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tiponota',
            field=models.CharField(max_length=50, verbose_name='Tipo da nota'),
        ),
    ]
