# Generated by Django 3.2.8 on 2021-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_pagamento_tiponota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='anotacoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anotaçoes'),
        ),
    ]
