# Generated by Django 3.2.8 on 2021-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_cronograma_anotacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contrato_locacao',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descriçao'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
    ]
