# Generated by Django 3.2.8 on 2021-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211029_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_acao',
            name='prazo',
            field=models.IntegerField(default=0, verbose_name='Prazo'),
            preserve_default=False,
        ),
    ]
