# Generated by Django 3.2.8 on 2021-11-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sede_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacao',
            name='descricao',
            field=models.CharField(default='', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aprovacao',
            name='setor',
            field=models.CharField(max_length=50, verbose_name='Setor'),
        ),
    ]
