# Generated by Django 3.2.8 on 2021-11-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20211107_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacao',
            name='descricao',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição'),
        ),
    ]
