# Generated by Django 3.2.8 on 2021-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_aprovacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacao',
            name='descricao',
            field=models.CharField(default='Teste', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
