# Generated by Django 3.2.8 on 2022-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_aprovacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagem',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipo_status',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipolocacao',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipopagto',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
