# Generated by Django 3.2.8 on 2022-05-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20220512_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao_Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descriçao')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acao', verbose_name='açao')),
                ('memorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.memorial', verbose_name='memorial')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_manutencao', to='core.status', verbose_name='status')),
                ('status_geral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_geral_manutencao', to='core.status', verbose_name='status geral')),
            ],
            options={
                'verbose_name': 'Solicitação de Manutenção',
                'verbose_name_plural': 'Solicitações de Manutenção',
            },
        ),
        migrations.CreateModel(
            name='Aquisicao_Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descriçao')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acao', verbose_name='açao')),
                ('memorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.memorial', verbose_name='memorial')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_aquisicao', to='core.status', verbose_name='status')),
                ('status_geral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_geral_aquisicao', to='core.status', verbose_name='status geral')),
            ],
            options={
                'verbose_name': 'Solicitação de Aquisição',
                'verbose_name_plural': 'Solicitações de Aquisição',
            },
        ),
    ]
