# Generated by Django 3.2.8 on 2022-05-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_aquisicao_acao_manutencao_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_locacao',
            name='trp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trp', verbose_name='numero_trp'),
        ),
        migrations.CreateModel(
            name='Sede_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('dataminuta', models.DateField(verbose_name='Data Minuta')),
                ('datadca', models.DateField(verbose_name='Data DCA')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('licitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.licitacao', verbose_name='Licitação')),
                ('manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manutencao_acao', verbose_name='Manutenção')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sede Manutenção',
                'verbose_name_plural': 'Sede Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Sede_Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('dataminuta', models.DateField(verbose_name='Data Minuta')),
                ('datadca', models.DateField(verbose_name='Data DCA')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aquisicao_acao', verbose_name='Aquisição')),
                ('licitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.licitacao', verbose_name='Licitação')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sede Aquisição',
                'verbose_name_plural': 'Sedes Aquisição',
            },
        ),
        migrations.CreateModel(
            name='Pagamento_Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parcela')),
                ('qtde_parcelas', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dataprevnota', models.DateField(verbose_name='Data Prev Nota')),
                ('tiponota', models.CharField(max_length=50, verbose_name='Tipo da nota')),
                ('numnota', models.IntegerField(verbose_name='Numero da Nota')),
                ('dataemissnota', models.DateField(verbose_name='Data de Emisso da Nota')),
                ('serienota', models.CharField(max_length=100, verbose_name='Série da Nota')),
                ('xml', models.CharField(max_length=100, verbose_name='XML')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aquisicao_acao', verbose_name='Aquisição')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
                ('tipo_pagto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopagto', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento Aquisição',
                'verbose_name_plural': 'Pagamentos Aquisição',
            },
        ),
        migrations.CreateModel(
            name='Cronograma_Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('datainicio', models.DateField(verbose_name='Data Inicial')),
                ('datafim', models.DateField(verbose_name='Data Final')),
                ('anotacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aquisicao_acao', verbose_name='Aquisição')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cronograma Aquisição',
                'verbose_name_plural': 'Cronogramas Aquisições',
            },
        ),
        migrations.CreateModel(
            name='Contrato_Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('processo', models.CharField(max_length=50, verbose_name='Processo')),
                ('dataprocesso', models.DateField(verbose_name='Data do Processo')),
                ('instrcontratual', models.CharField(max_length=50, verbose_name='Instrumento Contratual')),
                ('datacontrato', models.DateField(verbose_name='Data do Contrato')),
                ('valorservico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('valorlocacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Locação')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aquisicao_acao', verbose_name='Aquisição')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contrato Aquisição',
                'verbose_name_plural': 'Contratos Aquisição',
            },
        ),
        migrations.CreateModel(
            name='Compras_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.CharField(default='', max_length=100, null=True, verbose_name='Observaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('sede', models.BooleanField(verbose_name='Sede')),
                ('manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manutencao_acao', verbose_name='acao')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='status')),
                ('trp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trp', verbose_name='tRP')),
            ],
            options={
                'verbose_name': 'Compras - Manutençao',
                'verbose_name_plural': 'Compras - Manutençao',
            },
        ),
        migrations.CreateModel(
            name='Compras_Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.CharField(default='', max_length=100, null=True, verbose_name='Observaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('sede', models.BooleanField(verbose_name='Sede')),
                ('aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aquisicao_acao', verbose_name='ação')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='status')),
                ('trp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trp', verbose_name='tRP')),
            ],
            options={
                'verbose_name': 'Compras - Aquisiçao',
                'verbose_name_plural': 'Compras - Aquisiçao',
            },
        ),
    ]
