# Generated by Django 3.2.8 on 2022-05-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220529_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parcela')),
                ('qtde_parcelas', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dataprevnota', models.DateField(verbose_name='Data Prev Nota')),
                ('tiponota', models.CharField(max_length=50, verbose_name='Tipo da nota')),
                ('numnota', models.IntegerField(verbose_name='Numero da Nota')),
                ('dataemissnota', models.DateField(verbose_name='Data de Emisso da Nota')),
                ('serienota', models.CharField(max_length=100, verbose_name='Série da Nota')),
                ('xml', models.CharField(max_length=100, verbose_name='XML')),
                ('anotacoes', models.CharField(max_length=100, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manutencao_acao', verbose_name='Manutenção')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
                ('tipo_pagto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopagto', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento Manutenção',
                'verbose_name_plural': 'Pagamentos Manutenção',
            },
        ),
        migrations.CreateModel(
            name='Cronograma_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('datainicio', models.DateField(verbose_name='Data Inicial')),
                ('datafim', models.DateField(verbose_name='Data Final')),
                ('anotacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anotaçoes')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manutencao_acao', verbose_name='Manutenção')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cronograma Manutenção',
                'verbose_name_plural': 'Cronogramas Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Contrato_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data e hora de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('processo', models.CharField(max_length=50, verbose_name='Processo')),
                ('dataprocesso', models.DateField(verbose_name='Data do Processo')),
                ('instrcontratual', models.CharField(max_length=50, verbose_name='Instrumento Contratual')),
                ('datacontrato', models.DateField(verbose_name='Data do Contrato')),
                ('valorservico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('valorlocacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Locação')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manutencao_acao', verbose_name='Manutenção')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contrato Manutenção',
                'verbose_name_plural': 'Contratos Manutenção',
            },
        ),
    ]
