# Generated by Django 3.2.8 on 2022-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_contrato_manutencao_cronograma_manutencao_pagamento_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicao_acao',
            name='data_cadastro',
            field=models.DateField(null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AddField(
            model_name='locacao_acao',
            name='data_cadastro',
            field=models.DateField(null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AddField(
            model_name='manutencao_acao',
            name='data_cadastro',
            field=models.DateField(null=True, verbose_name='Data de cadastro'),
        ),
    ]
