# Generated by Django 3.2.8 on 2022-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20220917_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquisicao_acao',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descriçao'),
        ),
        migrations.AlterField(
            model_name='locacao_acao',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descriçao'),
        ),
        migrations.AlterField(
            model_name='manutencao_acao',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descriçao'),
        ),
    ]
