# Generated by Django 3.2.8 on 2022-09-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220918_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicao_acao',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='manutencao_acao',
            name='acao',
        ),
    ]
