# Generated by Django 3.2.8 on 2022-10-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_locacao_acao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao_acao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Statuses', to='core.status', verbose_name='status'),
        ),
    ]
